insert into itc_adresse (strasse, hausnr, plz, ort) values ('Swallow', '1', null, 'Changle');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Memorial', '534', '34260', 'Chanuman');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Algoma', '9', '5297', 'Rožna Dolina');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Merry', '36', null, 'Côn Sơn');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Shopko', '16', null, 'Watsa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Little Fleur', '93', '3800-525', 'Cabeço');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sheridan', '7', '4765-190', 'Riba de Ave');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Express', '3836', '052038', 'Yarumal');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Nobel', '68', null, 'Zhanghua');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Grasskamp', '61', '2253', 'Gálvez');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cherokee', '216', '3037', 'Drammen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Arapahoe', '86', null, 'New Yekepa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Petterle', '978', '330 12', 'Horní Bříza');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hintze', '2', '407 53', 'Rumburk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Onsgard', '4', '94101', 'Kunri');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kedzie', '85956', null, 'Fenshui');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Nancy', '4968', null, 'Merke');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Haas', '64196', null, 'Yenakiyeve');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Blue Bill Park', '4', 'MD-4734', 'Edineţ');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Carpenter', '776', '22-650', 'Łaszczów');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Saint Paul', '96871', '6333', 'Portorož');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Trailsway', '03', null, 'Kirgili');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Coleman', '572', '36005', 'Pontevedra');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pearson', '46', '433913', 'Selizharovo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Artisan', '28', null, 'Xiaoying');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hazelcrest', '01564', null, 'Mandikbatu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lyons', '18', null, 'Sorodot');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Little Fleur', '35439', '8307', 'Catriel');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eagan', '790', null, 'Sembungan Kidul');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Montana', '7189', '2440-341', 'Casal do Relvas');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Blue Bill Park', '4', '303036', 'Mtsensk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stoughton', '76445', '4515', 'Mauraro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Magdeline', '9', null, 'Changma');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Goodland', '3', null, 'Yako');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mandrake', '92', '2530-631', 'Ribamar');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Declaration', '16780', '366526', 'Shalazhi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Village', '67', null, 'Shazikou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Thompson', '1754', '94364 CEDEX', 'Bry-sur-Marne');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mayfield', '30', null, 'Wakefield');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Manitowish', '21819', '960-1476', 'Ishikawa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dovetail', '609', null, 'Qiaotou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stuart', '936', '7646', 'Pécs');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Carey', '6814', null, 'Matadi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sage', '824', '66180', 'Wang Sai Phun');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sloan', '869', '801 84', 'Gävle');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fremont', '5739', null, 'Lamadong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Comanche', '20', null, 'Luoping');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Prentice', '604', '7320', 'Ресен');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Corscot', '045', null, 'Changtang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Arkansas', '50532', null, 'Mandala');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Erie', '142', null, 'Mungwi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Portage', '48', '30061', 'Marietta');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ridgeway', '22777', null, 'Potulando');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Linden', '746', null, 'Bojen Kulon');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Aberg', '7', '853 56', 'Sundsvall');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Florence', '9', '58-240', 'Piława Górna');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Thackeray', '4556', null, 'Ngembel');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cody', '738', null, 'Tangzhuang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sundown', '53315', null, 'Kuaro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Maple Wood', '47', '35009 CEDEX', 'Rennes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('North', '0837', '21210', 'Wang Chan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Muir', '3879', '971 29', 'Luleå');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Petterle', '402', null, 'Shatou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Donald', '4', null, 'Ochobo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Erie', '68', '69405-000', 'Iranduba');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eastwood', '584', '45700-000', 'Itapetinga');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Southridge', '94233', '59304 CEDEX', 'Valenciennes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lindbergh', '07962', null, 'Novhorod-Sivers’kyy');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Prairieview', '71885', null, 'Tegalrejo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Melrose', '962', null, 'Funan Chengguanzhen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Everett', '09', null, 'Xiaochengzi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Karstens', '24751', '10260', 'Phra Khanong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ludington', '963', null, 'Smederevo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dixon', '98', '77386', 'Spring');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Arapahoe', '78', null, 'Ubajami');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cambridge', '16097', '769-0105', 'Kashihara');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Monument', '74', null, 'Gardēz');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dwight', '0', null, 'Bantawora');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bellgrove', '40998', null, 'Yongfu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Jana', '5', '82001', 'Tānk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Logan', '02860', null, 'Tall aḑ Ḑamān');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Susan', '366', '633260', 'Ordynskoye');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hauk', '52', null, 'Maralal');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Spohn', '5', '70690', 'Seremban');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kenwood', '3', '312 31', 'Laholm');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Comanche', '1', '99200-000', 'Guaporé');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Maryland', '4975', '54730', 'San Isidro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Gulseth', '9', '14085 CEDEX 9', 'Caen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Surrey', '6880', '142279', 'Obolensk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dawn', '5743', '717 00', 'Havířov');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Novick', '495', '3308', 'San Guillermo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Morning', '6604', '5050-223', 'Peso da Régua');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Linden', '6053', null, 'Bilajari');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fuller', '9569', '353996', 'Solnechnyy');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Coolidge', '753', '264 36', 'Klippan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Northfield', '82', '2622', 'Manaulanan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Farragut', '237', null, 'Taoyuan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Carpenter', '963', '32700', 'Otaniemi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Farragut', '90', '542018', 'Herrán');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Truax', '2370', null, 'Cimara');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fisk', '243', null, 'Nagarakembang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eagle Crest', '2403', '7541', 'Kaynardzha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kennedy', '9', null, 'Fengcun');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Roth', '9', null, 'Andoany');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Golden Leaf', '8', null, 'Wangshi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Buell', '7', '1154', 'Sangali');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Erie', '0749', '11518', 'La Romana');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dunning', '0113', '1225', 'Јегуновце');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Waywood', '385', null, 'Huangwan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Loeprich', '06577', 'EH52', 'Burnside');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Towne', '7735', '456505', 'Novosineglazovskiy');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mifflin', '176', null, 'Aygeshat');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Prairieview', '156', '131 22', 'Nacka');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fieldstone', '1', '78897 CEDEX', 'Saint-Quentin-en-Yvelines');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('David', '424', null, 'Tempursari Wetan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Troy', '534', '347037', 'Nekhayevskiy');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Caliangt', '6', '6306', 'Valencia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kinsman', '2', null, 'Montijo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Briar Crest', '76', null, 'Namangan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Muir', '55701', null, 'Oruro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('American', '63272', null, 'Texistepeque');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Gale', '28369', '97078', 'Würzburg');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Declaration', '4623', '72130', 'Sam Chuk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Crownhardt', '84013', '141667', 'Reshetnikovo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('La Follette', '583', null, 'Junik');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Crest Line', '78', null, 'Hongmiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lukken', '8384', null, 'Bongor');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mallard', '4', '4419', 'Ocampo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Express', '32053', '9103', 'Sagay');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Barnett', '695', '50101', 'Liberia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sachtjen', '9', null, 'Wangba');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Trailsway', '4010', '88661', 'Kota Kinabalu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bashford', '70', '385', 'Miðvágur');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dovetail', '973', '356825', 'Budënnovsk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Spohn', '2065', null, 'Nahāvand');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elgar', '951', '73379 CEDEX', 'Le Bourget-du-Lac');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('High Crossing', '005', null, 'Port-aux-Français');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Prentice', '9', null, 'Rizómilos');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Upham', '200', null, 'Seria');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Scott', '8', '33233', 'Miami');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hooker', '9615', '17980-000', 'Panorama');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Clove', '11', null, 'Arenal');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dryden', '08', null, 'Skalánion');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mallard', '26144', '234 27', 'Lomma');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Buell', '07618', null, 'Bukavu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Judy', '5210', '2718', 'Cervantes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lien', '1415', '14683', 'Rochester');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Nova', '3', null, 'Guane');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bashford', '500', null, 'Totoral');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bay', '2691', '9337', 'Dobrich');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Forest', '723', null, 'Fratar');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hagan', '26010', null, 'Yolöten');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rowland', '26', '65110', 'Bang Krathum');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Linden', '2', null, 'Al Bājūr');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Old Shore', '12', null, 'Moutsamoudou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fuller', '27267', '1630', 'Upi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Colorado', '6', '171939', 'Maksatikha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Graedel', '47', null, 'Sampungu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Alpine', '586', '197758', 'Sertolovo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Michigan', '1486', null, 'Zhuxing Chaoxianzu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Roxbury', '17591', null, 'Hongdun');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Thompson', '6', '50009 CEDEX', 'Saint-Lô');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oak Valley', '6', null, 'Bureng');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Northland', '50', 'K7R', 'Skatepark');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Waywood', '43110', '44324 CEDEX 3', 'Nantes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fordem', '751', '861-3923', 'Kashiwa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Milwaukee', '44', null, 'Liuji');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bayside', '248', null, 'Lethem');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Carberry', '3', null, 'Taiping');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('John Wall', '7', null, 'Darnah');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Menomonie', '7', '663974', 'Ural');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fieldstone', '16307', '992-0778', 'Takaoka');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('East', '34', '12169', 'Berlin');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Autumn Leaf', '313', null, 'Mumias');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Drewry', '8391', '561 81', 'Kunvald');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pine View', '5', '24758 CEDEX', 'Trélissac');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ryan', '05754', null, 'Tuqiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cambridge', '7694', null, 'Shuiying');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kensington', '765', null, 'Hekou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rigney', '97117', null, 'Pomacocha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('David', '59804', null, 'Jingmen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pierstorff', '133', null, 'Dayangqi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cottonwood', '025', '33-181', 'Siemiechów');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lawn', '6436', null, 'Panjerrejo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Corry', '7646', '43610', 'Toledo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pennsylvania', '44', null, 'Caujul');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Corry', '185', null, 'Nanqiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cherokee', '626', '791 91', 'Falun');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Huxley', '50452', '8038', 'Bodø');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bartelt', '912', '364 71', 'Bochov');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Alpine', '1', null, 'Xiagong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('American Ash', '3306', null, 'Nadi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fulton', '69382', null, 'Krajan Tanjungrejo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Comanche', '796', null, 'Ongi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Glacier Hill', '51064', null, 'La Libertad');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kennedy', '1', '30323', 'Atlanta');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mccormick', '2', null, 'Pocohuanca');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Washington', '8783', null, 'Sirāhā');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eastlawn', '064', null, 'Jianshe');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kinsman', '75', '3109', 'Buliran Segundo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Swallow', '4078', '79260-000', 'Bela Vista');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Laurel', '18383', '30674', 'Ipoh');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Prairieview', '847', '1485', 'Navotas');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dakota', '904', null, 'Sunjia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rowland', '9', null, 'Novi Travnik');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Shelley', '0421', '121 12', 'Johanneshov');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('South', '48', null, 'Atafu Village');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Armistice', '6', null, 'Yŏnggwang-ŭp');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hauk', '80', null, 'Dodola');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('West', '4', '642 82', 'Flen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ryan', '92471', '509-0147', 'Kakamigahara');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rigney', '61', null, 'Zongjia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Crest Line', '64', null, 'Da’an');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Merchant', '000', null, 'Onitsha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Tony', '613', null, 'Ciyu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Moose', '589', '676015', 'Skovorodino');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('West', '0087', '981-1502', 'Oyama');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Knutson', '7794', '43-385', 'Jasienica');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Blackbird', '74', null, 'Skokovi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Memorial', '61800', '6025', 'Oslob');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fair Oaks', '9', '58700-000', 'Patos');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mitchell', '3', '25005', 'Lleida');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Calypso', '5', '3220', 'Monte Caseros');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sunbrook', '36', null, 'Rejasa Kaja');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Melody', '614', 'T8R', 'Morinville');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Westridge', '13', null, 'Taoyuan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Golf Course', '873', null, 'Armopa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Anthes', '116', '29905', 'Beaufort');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ryan', '19', null, 'Kasba Tadla');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Summit', '7', '55100', 'Kuala Lumpur');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lukken', '6', '4325', 'Lalig');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Gateway', '979', null, 'Jugantang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('7th', '537', '452200', 'Chekmagush');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Forest Run', '76', null, 'Genengan Kulon');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Clarendon', '581', null, 'Waishan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dixon', '8298', '4810-050', 'Loureiro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Melby', '75808', '96400-000', 'Bagé');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Orin', '52906', null, 'Bealanana');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hoffman', '552', 'H16', 'Manorhamilton');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Spaight', '0784', '4690-480', 'Ribeira');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Warner', '21', null, 'Popil''nya');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Logan', '5921', null, 'Nzega');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Almo', '32', '763528', 'El Cerrito');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Victoria', '5993', null, 'Bukonyo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ruskin', '9', '3450-405', 'Gândara');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ridgeview', '9', null, 'Qingshi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elgar', '1107', '33710', 'Saint Petersburg');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Derek', '19278', '73216 CEDEX', 'Aime');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pleasure', '22', '62-604', 'Kościelec');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lerdahl', '872', '66053', 'Los Nogales');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Swallow', '20594', null, 'Sangumata');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('2nd', '948', null, 'Ansan-si');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Holmberg', '0248', null, 'Ringinrejo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Norway Maple', '111', '31165', 'Atlanta');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Washington', '5', null, 'San Vicente de Bique');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Parkside', '70971', null, 'Igarra');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lawn', '379', '453550', 'Tukan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Jay', '0975', '39180', 'Warburton');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Schurz', '3764', null, 'Moch');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mandrake', '365', null, 'Tangzhuang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Glacier Hill', '175', '309-1127', 'Shimodate');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Merchant', '0', '671360', 'Bichura');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ridge Oak', '34', '112 83', 'Stockholm');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Clemons', '78', null, 'Panglanjan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kensington', '176', null, 'Chợ Lầu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sage', '60805', '186730', 'Lakhdenpokh’ya');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('5th', '10', '10801', 'Guadalupe');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Swallow', '4950', '356555', 'Vladimir');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('South', '063', '15670', 'Kota Bharu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Petterle', '3666', null, 'Sillamäe');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Carpenter', '5', '3832', 'Hājīganj');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Melby', '4', '36-067', 'Hyżne');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('6th', '9504', '62-090', 'Rokietnica');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Saint Paul', '70997', null, 'Meghrashen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fuller', '84548', '519-3674', 'Owase');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hallows', '05', null, 'Nanzhao Chengguanzhen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Di Loreto', '875', null, 'Bahuang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Merry', '958', '3503', 'Solana');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('American Ash', '395', '7409', 'Deventer');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Memorial', '9', null, 'Rumphi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Laurel', '496', '334 52', 'Merklín');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bonner', '20', '41905', 'Migrate');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lake View', '5221', null, 'Katumba');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Burning Wood', '96309', null, 'Anyang-si');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mandrake', '7432', null, 'Yantai');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lotheville', '87233', null, 'Xianghu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Graceland', '1', null, 'Zhetang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fulton', '81', null, 'Xiongguan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hoard', '9179', '7005-764', 'São Miguel de Machede');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Troy', '072', '963-0107', 'Asaka');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Esch', '5', null, 'Majiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Miller', '8', null, 'Aiánteio');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rigney', '1113', 'V7Y', 'West End');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Park Meadow', '6', null, 'Tekes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Starling', '4', '512 93', 'Svenljunga');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Maywood', '2', '456862', 'Tayginka');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('La Follette', '08214', null, 'Huadi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mesta', '188', null, 'Kayes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bartillon', '16411', null, 'Jindong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Weeping Birch', '7', '94525 CEDEX 1', 'Rungis');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Gateway', '642', null, 'Temuco');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Quincy', '84', null, 'Mýki');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cascade', '147', null, 'Four Cross Roads');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Monterey', '93', '32-445', 'Bęczarka');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Clove', '090', null, 'Bagu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Nobel', '9599', null, 'Huangshui');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Darwin', '080', null, 'Huế');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Delaware', '74', null, 'Pendolo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fairview', '43119', null, 'Panjerrejo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('2nd', '66059', '21-109', 'Uścimów Stary');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Warrior', '8130', '6401', 'Bobon');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dwight', '5', null, 'Awilega');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ilene', '6964', null, 'Perjuangan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Chinook', '1', null, 'Gaoqiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Marcy', '91152', null, 'Tabou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Russell', '68', null, 'Lewobelek');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Saint Paul', '25409', '2601', 'La Trinidad');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Holmberg', '1916', '338 08', 'Zbiroh');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stuart', '5', '1150', 'Maketu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Springs', '760', null, 'San Ignacio');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stone Corner', '81073', null, 'Jibu Hulangtu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Debs', '04', '11604', 'Pedro García');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Monterey', '85', '89295-000', 'Rio Negrinho');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cardinal', '0092', null, 'Bukabu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Granby', '94', '5040', 'Ponong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pleasure', '36', '51690', 'San Miguel');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('5th', '84046', null, 'Maştağa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Macpherson', '0638', 'A86', 'Leixlip');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mallard', '8821', null, 'La Jicaral');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Maryland', '39962', '186424', 'Segezha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eagle Crest', '6', '51462', 'La Mesa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Packers', '0', null, 'Slavs’ke');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lyons', '621', null, 'Baih');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mayfield', '24', '4690-480', 'Ribeira');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Buell', '546', null, 'Tiechang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Linden', '962', '799-2441', 'Hōjō');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stephen', '8710', null, 'Broshniv-Osada');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Thierer', '2246', null, 'Pinghu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Corry', '4', '4415-719', 'Moses');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cordelia', '17007', '16146', 'Genova');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Talisman', '97', null, 'Kongoussi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Shopko', '3', null, 'Vũng Tàu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Parkside', '157', null, 'Peicheng');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Autumn Leaf', '68136', '171658', 'Novokuz’minki');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hoffman', '43520', '763049', 'Buga');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Nancy', '10004', null, 'Qingfa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Caliangt', '0', '473008', 'Mompós');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Starling', '032', null, 'Calibishie');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kinsman', '4035', null, 'Zhangjiachang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Eliot', '079', null, 'Werasari');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Ryan', '77907', '4990-585', 'Sobral');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oriole', '9', '09-412', 'Maszewo Duże');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Upham', '551', null, 'Văn Điển');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dryden', '48', '57910-000', 'Matriz de Camaragibe');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Everett', '4', null, 'Lazeshchyna');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Westend', '3', '41976 CEDEX 9', 'Blois');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Crownhardt', '5798', null, 'Baitashan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Harper', '51', null, 'Truskavets');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bonner', '38', '96970', 'Mili');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Randy', '67', null, 'Pershotravneve');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Transport', '9', '13010', 'Santa Bárbara');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mallard', '983', 'L2T', 'Swan Hills');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Springs', '96', 'J8Y', 'Angus');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Morrow', '65', '32-015', 'Targowisko');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bowman', '8132', '68-343', 'Brody');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Marquette', '943', '76590-000', 'São Miguel do Araguaia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Debra', '7383', null, 'San Jerónimo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elka', '100', '6354', 'La Cumbre');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Gale', '1461', null, 'Tsaratanana');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Homewood', '37', null, 'Ararat');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Manufacturers', '12787', '3917', 'Porsgrunn');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Milwaukee', '14728', '63-816', 'Gostyń');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Anhalt', '30658', null, 'Selínia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Memorial', '105', '5110', 'Tilik');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Vermont', '4677', null, 'Liujiage');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dawn', '65813', '2709', 'Galimuyod');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hallows', '5', null, 'Cochabamba');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Toban', '31377', '23110', 'Khlong Yai');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Moulton', '9415', null, 'Magugu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Knutson', '30311', '20420', 'Washington');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Iowa', '8322', null, 'Kuma');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fordem', '5039', null, 'Brovary');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Valley Edge', '1235', '4770-370', 'Alminhas');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dapin', '61840', null, 'Lüjiabao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Brickson Park', '3441', '27204 CEDEX', 'Vernon');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Blaine', '7', '07309 CEDEX', 'Tournon-sur-Rhône');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Quincy', '9', null, 'Ulaandel');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fairview', '5', null, 'Dafang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cottonwood', '06', null, 'Ningxin');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lakewood Gardens', '08055', '33680', 'Tampa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Weeping Birch', '355', '28300-000', 'Itaperuna');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Redwing', '03167', '630008', 'Armenia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mayfield', '53', null, 'Anaráchi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oneill', '6', null, 'Cikadu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mitchell', '8', null, 'Zhonglong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oneill', '31', '5100-121', 'Sé');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sunfield', '651', null, 'Gaoqiao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hoffman', '8552', 'G5R', 'Rivière-du-Loup');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oak Valley', '2789', null, 'Sebuku');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Arapahoe', '1', null, 'Donghe');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bartillon', '67', '945-0812', 'Handa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bluestem', '12189', '5214', 'Mauhao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Debra', '5', null, 'Ḩarastā');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mockingbird', '976', '75044', 'Garland');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Holmberg', '53', null, 'Gwadabawa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stang', '8', null, 'Nalbandyan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Summerview', '75', '665689', 'Rudnogorsk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dunning', '84', '35940-000', 'Rio Piracicaba');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kim', '8', null, 'Luocheng');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Northridge', '1158', null, 'Rawasan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Golf', '4046', null, 'Lukou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Brown', '00987', null, 'Trinidad');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sherman', '703', null, 'Iquipi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cottonwood', '86664', null, 'Dafengdui');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mccormick', '615', null, 'Zhoukou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('3rd', '1718', null, 'Boyu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sachtjen', '9', null, 'Pasiripis');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lawn', '5', '68540-000', 'Conceição do Araguaia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Evergreen', '02671', null, 'Wŏnsan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sunnyside', '087', null, 'Oropós');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sycamore', '59089', '43-200', 'Pszczyna');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bobwhite', '1', '4606', 'Luklukan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('David', '107', null, 'Longnawang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Golf', '028', 'G8A', 'Beaverlodge');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Summer Ridge', '12', null, 'Rinang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Loeprich', '4', null, 'Tianzishan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('John Wall', '8935', '8714', 'Dologon');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Forest Run', '3', '665911', 'Kultuk');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bellgrove', '08860', null, 'Bajia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mccormick', '3', '056077', 'Betania');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bluestem', '30515', null, 'Xin’an');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Scoville', '33308', null, 'Pachīr wa Āgām');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Erie', '65', 'L-9391', 'Reisdorf');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bashford', '6', null, 'Kopen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Kensington', '60', null, 'Tilmi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Coolidge', '450', '27710', 'Durham');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Glendale', '9304', null, 'Platičevo');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Goodland', '0', null, 'Jiangwan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mayfield', '2', null, 'Tiantai Chengguanzhen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bartillon', '1', null, 'Rancanyenang');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Jackson', '912', null, 'Nanzhai');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Stephen', '005', null, 'Agbor');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sutherland', '2601', '01508', 'Kangar');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Laurel', '98', '2530-254', 'Seixal');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Magdeline', '42880', null, 'Xinchong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Delladonna', '33', null, 'Ad Dasmah');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lakewood Gardens', '85679', null, 'Hola Prystan’');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Jenna', '9692', '2445-764', 'Martingança-Gare');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('4th', '05211', null, 'Ccuntuma');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Rutledge', '4', null, 'Jīt');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Shasta', '3', null, 'Shuishaping');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sullivan', '92', '4427', 'Cafayate');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Almo', '828', '2426', 'La Francia');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elmside', '67', null, 'Fundong');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Knutson', '93', '387 73', 'Bavorov');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lillian', '40', '603 72', 'Norrköping');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sherman', '2', null, 'Yylanly');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mallard', '57848', null, 'Shawan');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sugar', '0139', '84-107', 'Jastrzębia Góra');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lawn', '84', '6126', 'Calatrava');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Vernon', '1', '1980', 'Tanay');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Coleman', '01342', null, 'Lujing Zhen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Becker', '56373', null, 'Zhuping');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('School', '7', null, 'Vilcún');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Calypso', '7311', null, 'Muzi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elgar', '3', '91154 CEDEX', 'Étampes');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Bultman', '22', null, 'Qianzhou');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Claremont', '3952', null, 'Hulu');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Iowa', '3', null, 'Lae');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Clarendon', '88405', null, 'La Libertad');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Northridge', '86307', '33604 CEDEX', 'Pessac');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lukken', '835', null, 'Wanli');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Canary', '01', null, 'Anzi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Morningstar', '0', '76418 CEDEX 9', 'Rouen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Erie', '1', null, 'Shuangxi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Warbler', '4879', '735 35', 'Horní Suchá');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mayfield', '61667', null, 'Soriano');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fremont', '4624', '78975-000', 'Cacoal');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Cambridge', '39', '186806', 'Lyaskelya');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Pepper Wood', '82', '88000-000', 'Itacorubi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('International', '91444', null, 'Singajaya');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Birchwood', '8633', '5439', 'Villa Lugano');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Homewood', '73', '5172', 'Piquillín');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Vernon', '1750', null, 'Solok');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Fulton', '5545', '64-970', 'Piła');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Sloan', '4', null, 'Bondowoso');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Schurz', '2395', '65218-000', 'Matinha');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Mariners Cove', '5855', '33811', 'Lakeland');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Elgar', '0394', '2460-105', 'Alfeizerão');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Lindbergh', '34', null, 'Karafao');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Summit', '1', null, 'Sergelen');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Oriole', '780', '6060-205', 'Ladoeiro');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Dexter', '09314', null, 'Sijiqing');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Goodland', '410', null, 'Gorgoram');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Northwestern', '0787', '18110', 'Kaeng Khoi');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('2nd', '83452', '55340-000', 'Águas Belas');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Leroy', '3305', '98880', 'La Foa');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Hansons', '72', '649-1537', 'Gobō');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Schmedeman', '39', '9505', 'Kroonstad');
insert into itc_adresse (strasse, hausnr, plz, ort) values ('Scott', '4237', null, 'Santo Domingo');
